### ISSUE TITLE
No vertical sort

### ISSUE THREAD

**Issue by fela98** [martijn00/XamarinItemTouchHelper#3]
Somehow, with the Android Support version 24, it's impossible to sort vertically. Only the horizontal swipe is still working.

**Comment by NikasZalias** [comment]
I have the same issue....

**Comment by NikasZalias** [comment]
@fela98 have you solved this problem?? @martijn00 could you please help??

**Comment by martijn00** [comment]
This probably needs an update to the latest Support Libraries.

**Comment by NikasZalias** [comment]
@martijn00 I updated all libraries to the latest versions!

**Comment by martijn00** [comment]
Yes, what i mean is that the XamarinItemTouchHelper needs an update to the latest and then put a new nuget package out.

**Comment by NikasZalias** [comment]
Could you please explain this in steps what I need to do? What do you mean by put a new nuget package out?

**Comment by martijn00** [comment]
You need to fork this repository. Then update all the nuget packages. After that fix issue's that might pop up. Then you make a Pull Request to this here, and after i merge it, i will put the nuget package update online.

**Comment by NikasZalias** [comment]
@martijn00 just made a pull request!

**Comment by marijn00** [comment]
No
Op 30 okt. 2017 14:15 schreef "NikasZalias" <notifications@github.com>:

**Comment by NikasZalias** [comment]
@martijn00 Have you managed to find the bug??

**Comment by marijn00** [comment]
Nein
Op 2 nov. 2017 11:21 schreef "NikasZalias" <notifications@github.com>:

**Comment by NikasZalias** [comment]
@martijn00 I noticed that When I try to drag an item I get notified by this message "Start drag has been called but swiping is not enabled". But also I noticed that in RecyclerListAdapter class the overriden OnItemMove method is never called!

**Comment by marijn00** [comment]
You should delete it
Op 2 nov. 2017 15:06 schreef "NikasZalias" <notifications@github.com>:
